kind: pipeline
name: default
steps:
  - name: build
    image: tindzk/seed:0.1.7-15-gcf4cb2b0
    commands:
      - apk add --no-cache yarn
      - yarn add jsdom object-sizeof
      - seed --build=build211.toml bloop
      - bloop compile pine-native
      - bloop test pine-jvm
      - rm -rf .bloop build
      - seed --build=build212.toml bloop
      - bloop test pine-jvm pine-js
      - rm -rf .bloop build
      - seed --build=build213.toml bloop
      - bloop test pine-jvm pine-js
      - bloop run pine-bench-jvm -- fast
      - bloop run pine-bench-js  -- fast
